FROM python:3.11.9-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app/backend/

CMD ["celery", "-A", "backend.celery_app", "worker", "--loglevel=info"]